config/routes.rb
Rails.application.routes.draw do
  resources :projects, only: [:index]
  root 'projects#index'
  get 'playmates' => 'projects#playmates'

end

app/models/project.rb
class Project < ActiveRecord::Base
  def self.states(playmates)
    states = { 
      'AL'=> 0, 'AK'=> 0, 'AZ'=> 0, 'AR'=> 0, 'CA'=> 0, 'CO'=> 0, 'CT'=> 0, 'DE'=> 0, 'FL'=> 0, 'GA'=> 0,
      'HI'=> 0, 'ID'=> 0, 'IL'=> 0, 'IN'=> 0, 'IA'=> 0, 'KS'=> 0, 'KY'=> 0, 'LA'=> 0, 'ME'=> 0, 'MD'=> 0,
      'MA'=> 0, 'MI'=> 0, 'MN'=> 0, 'MS'=> 0, 'MO'=> 0, 'MT'=> 0, 'NE'=> 0, 'NV'=> 0, 'NH'=> 0, 'NJ'=> 0,
      'NM'=> 0, 'NY'=> 0, 'NC'=> 0, 'ND'=> 0, 'OH'=> 0, 'OK'=> 0, 'OR'=> 0, 'PA'=> 0, 'RI'=> 0, 'SC'=> 0,
      'SD'=> 0, 'TN'=> 0, 'TX'=> 0, 'UT'=> 0, 'VT'=> 0, 'VA'=> 0, 'WA'=> 0, 'WV'=> 0, 'WI'=> 0, 'WY'=> 0,
      'DC'=> 0, 'GU'=> 0, 'PW'=> 0, 'PR'=> 0, 'VI'=> 0
    }
    stateList = []
    playmates.each do |playmate|
      if playmate['birthplace']
        if playmate['birthplace']['state'].length > 2
          state = Project.stateKeys(playmate['birthplace']['state'].downcase)
        else
          state = playmate['birthplace']['state']
        end
        states[state] += 1 if states[state]
      end
    end
    states.each do |key, value|
      new_value = (300 - value) / 2 * 9
      stateList << { name: key, num: value, fillValue: new_value }
    end
    stateList
  end

  def self.hair_colors(playmates)
    colors = Hash.new 0
    playmates.each do |p|
      colors[p['haircolor']] += 1
    end
    colors
  end

  def self.stateKeys(state)
    keys = 
    { 
    'alabama' => :AL,
    'alaska' => :AK,
    'arizona' => :AZ,
    'arkansas' => :AR,
    'california' => :CA,
    'colorado' => :CO,
    'connecticut' => :CT,
    'delaware' => :DE,
    'florida' => :FL,
    'georgia' => :GA,
    'hawaii' => :HI,
    'idaho' => :ID,
    'illinois' => :IL,
    'indian' => :IN,
    'iowa' => :IA,
    'kansas' => :KS,
    'kentucky' => :KY,
    'louisiana' => :LA,
    'maine' => :ME,
    'maryland' => :MD,
    'massachusetts' => :MA,
    'michigan' => :MI,
    'minnesota' => :MN,
    'mississippi' => :MS,
    'missouri' => :MO,
    'montana' => :MT,
    'nebraska' => :NE,
    'nevada' => :NV,
    'new hampshire' => :NH,
    'new jersey' => :NJ,
    'new mexico' => :NM,
    'new york' => :NY,
    'north carolina' => :NC,
    'North dakota' => :ND,
    'ohio' => :OH,
    'oklahoma' => :OK,
    'oregon' => :OR,
    'pennsylvania' => :PA,
    'rhode island' => :RI,
    'south carolina' => :SC,
    'south dakota' => :SD,
    'tennessee' => :TN,
    'texas' => :TX,
    'utah' => :UT,
    'vermont' => :VT,
    'virginia' => :VA,
    'washington' => :WA,
    'west virginia' => :WV,
    'wisconsin' => :WI,
    'wyoming' => :WY,
    'Dcistrict of columbia' => :DC,
    'guam' => :GU,
    'palau' => :PW,
    'puerto rico' => :PR,
    'virgin islands' =>:'V'
    }
    keys[state].to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def playmates
    text = IO.read("#{Rails.root}/config/playmates.json")
    playmates = JSON.parse(text)
    states = Project.states(playmates)
    respond_to do |format|
      format.html { :playmates }
      format.json { render json: { playmates: playmates, states: states } }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params[:project]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_flyout.html.erb
<div class="row flyout" ng-class="flyout">
  <div class="col-md-10 col-md-offset-1">
  <div class="row resume">
      <div class="col-md-12 text-right">
      <span class="glyphicon glyphicon-remove nav-menu-close" aria-hidden="true" ng-click="flyout=''"></span>
      </div>
    </div>
    <div class="row about">
      <div class="col-md-12">
        Thanks for checking out my portfolio. I am a Sotware Engineer and UX Designer currently living in Washington DC. I am a huge fan of Ruby on Rails and AngularJS, but am starting to get into more real time stacks like Meteor. If you like a project that I have worked on or just want to grab coffee, please don't hesitate to drop me a note at <a href="mailto:rusnak@vt.edu" target="_top">rusnak@vt.edu</a>
      </div>
    </div>
    <div class="row resume">
      <div class="col-md-12 text-center">
        <a href="https://s3.amazonaws.com/2014Portfolio/Rusnak-3-14.pdf">RESUME</a>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-12">
          <div class="col-md-12 text-center">
            <ul class="nav nav-pills center-pills">
              <li><%= link_to icon('twitter'), 'https://twitter.com/ryanrusnak' %></li>
              <li><%= link_to icon('facebook'), 'https://www.facebook.com/ryan.rusnak.10' %></li>
              <li><%= link_to icon('github'), 'http://github.com/ryanrusnak' %></li>
            </ul>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="portfolioApp" ng-controller="MainCtrl">
<head>
  <title>RyanRusnak</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <% if flash[:notice] %>
      <div class="alert alert-info" role="alert"><%= notice %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-warning" role="alert"><%= alert %></div>
    <% end %>
    <span class="glyphicon glyphicon-menu-hamburger nav-menu" aria-hidden="true" ng-click="flyout='show-flyout'"></span>
    <%= render partial: 'layouts/flyout' %>
    <%= yield %>
  </div>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-29107672-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class=row ng-repeat="project in projects track by $index" ng-if="$index%3==0">
  <div class="col-sm-4 cell nopadding" ng-repeat="i in [$index,$index+1,$index+2]" ng-if="projects[i]!=null">
    <a class="navi"></a>
    <project class="project" data="projects[i]"></project>
 </div>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/playmates.html.erb
<!-- <script src="http://d3js.org/colorbrewer.v1.min.js"></script> -->
<div class="playvis row" ng-controller="PlayboyCtrl">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-8">
        <div id="usa-map"></div>
      </div>
      <ul class="col-md-4" id="list" >
        <li class="list-unstyled" ng-repeat="playmate in playmates | filter:{'birthplace': {'state' : state}}:true | orderBy: '-likes'">
          <playmate ng-class="tooltip" data="playmate" tooltip="tooltip"></playmate>
        </li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-12">
        <nvd3 id="hair-color" options="colorOptions" data="colorData"></nvd3>
      </div>
      <div class="col-md-6">
        <nvd3 id="measurements" options="measurementOptions" data="measurementData"></nvd3>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>